#!/usr/bin/env bash

IDCODE_START=38888888888
IDCODE_END=38888888889

# I astme kaal: 1 2 3 4 5 6 7 8 9 1
WEIGHTS1=(1 2 3 4 5 6 7 8 9 1)

# II astme kaal: 3 4 5 6 7 8 9 1 2 3
WEIGHTS2=(3 4 5 6 7 8 9 1 2 3)

for ((idcode = IDCODE_START; idcode < IDCODE_END; idcode++)); do
  chk=0
  for ((i = 0; i < ${#WEIGHTS1[@]}; i++)); do
    chk=$((chk + WEIGHTS1[i] * ${idcode:i:1}))
  done

  chk=$((chk % 11))

  if (($chk == 10)); then
      chk=0
      for ((i = 0; i < ${#WEIGHTS2[@]}; i++)); do
        chk=$((chk + WEIGHTS2[i] * ${idcode:i:1}))
      done
  
      chk=$((chk % 11))
      if (($chk == 10)); then
        chk=0
      fi
  fi
   
  if (($chk == ${idcode:10:1})); then
    cmd="ldapsearch -x -h ldap.sk.ee -b c=EE (serialNumber=$idcode) objectClass=top" 
    ldapsearch -x -h ldap.sk.ee -b c=EE "(serialNumber=$idcode)" "objectClass=top"
    sleep 3
  fi
done
